// Jose Bernardo Montano
// Jaret Raymond Rickel
// Annie Corinne Beaupre
import React, { useState, useEffect } from "react";
import ReactPaginate from "react-paginate";

// ViewOrgRequests show a table with all the request from organizations
// who are inviting a user to join them
function ViewOrgRequests({ name }) {
  // Hooks
  const [pendingOrgs, setPendingOrgs] = useState([]);
  const [pageCount, setPageCount] = useState(0);
  const [currentPage, setCurrentPage] = useState(0);
  const PER_PAGE = 5; // number of items to display per page
  const [error, setError] = useState("");

  const handleChangeStatus = (organization, status) => {
    console.log("Handle being called!");
    console.log(organization, status);
    // POST request
    fetch(`/change-org-status/${name}`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        organization,
        status,
      }),
    })
      .then((res) => res.json())
      .then((data) => {
        const index = pendingOrgs.findIndex(
          (pendingOrg) => pendingOrg.name === organization
        );

        const updatePendingOrgs = [...pendingOrgs];
        updatePendingOrgs.splice(index, 1);
        setPendingOrgs(updatePendingOrgs);
      })
      .catch((err) => {
        //
      });
  };

  useEffect(() => {
    // GET request
    fetch(`/get-pending-orgs/${name}`)
      .then((res) => res.json())
      .then((data) => {
        if (data && data.pendingOrgs.length === 0) {
          setError(`Hi ${name}! You have zero organizations Requests`);
        } else {
          console.log(data);
          setPendingOrgs(data.pendingOrgs);
          setPageCount(Math.ceil(data.pendingOrgs.length / PER_PAGE));
        }
      })
      .catch((err) => {
        console.error(err);
        setError("Error fetching pending organizations requests");
      });
  }, []);

  const handlePageClick = ({ selected: selectedPage }) => {
    setCurrentPage(selectedPage);
  };

  // Calculates offset
  const offset = currentPage * PER_PAGE;

  // Autogenerated content for table
  const currentPendingOrgs = pendingOrgs
    .slice(offset, offset + PER_PAGE)
    .map((pendingOrg) => (
      <tr
        key={pendingOrg.id}
        className="bg-blue-500 border-b border-blue-700 text-white font-semibold"
      >
        <td className="px-6 py-4 w-1/6">
          <button onClick={() => handleChangeStatus(pendingOrg.name, "accept")}>
            Accept
          </button>
          <span>&nbsp;&nbsp;&nbsp;/&nbsp;&nbsp;&nbsp;</span>
          <button
            onClick={() => handleChangeStatus(pendingOrg.name, "decline")}
          >
            Decline
          </button>
        </td>
        <td className="px-6 py-4">{pendingOrg.name}</td>
        <td className="px-6 py-4">{pendingOrg.leaderName}</td>
        <td className="px-6 py-4">{pendingOrg.people.length}</td>
      </tr>
    ));

  // Returns jsx code
  if (error === "Error fetching pending friends") {
    return (
      <div>
        <p className="font-bold text-md text-gray-600 mt-6 mx-8">{error}</p>
      </div>
    );
  }

  // Returns jsx code
  if (pendingOrgs.length !== 0) {
    return (
      <div>
        <div className="relative overflow-x-auto mx-10 mt-10 rounded-md">
          <table className="w-full text-md text-left text-white">
            <thead className="text-xs text-white uppercase bg-blue-700">
              <tr>
                <th className="w-1/6 px-6 py-3">Status</th>
                <th className="px-6 py-3">Organization</th>
                <th className="px-6 py-3">Leader</th>
                <th className="px-6 py-3">Size of Organization</th>
              </tr>
            </thead>
            <tbody>{currentPendingOrgs}</tbody>
          </table>
        </div>
        <div className="flex flex-row justify-center my-10">
          <ReactPaginate
            previousLabel={"← Previous"}
            nextLabel={"Next →"}
            pageCount={pageCount}
            onPageChange={handlePageClick}
            containerClassName={"flex space-x-4"}
            previousLinkClassName={
              "bg-blue-500 px-3 py-2 rounded-md text-md font-bold text-white"
            }
            nextLinkClassName={
              "bg-blue-500 px-3 py-2 rounded-md text-md font-bold text-white"
            }
            disabledClassName={"disabled"}
            activeClassName={
              "bg-blue-500 text-white px-3 py-1 rounded-md text-sm font-medium"
            }
          />
        </div>
      </div>
    );
  } else {
    return (
      <div>
        <p className="font-bold text-md text-gray-600 mt-6 mx-8">
          You don't have any organizations invites at the moment
        </p>
      </div>
    );
  }
}

export default ViewOrgRequests;
