// Jose Bernardo Montano
// Jaret Raymond Rickel
// Annie Corinne Beaupre

import React, { useState, useEffect } from "react";
import ReactPaginate from "react-paginate";

// View Friend shows a table of your friends and some stats
// about them
function ViewFriends({ name }) {
  const [friends, setFriends] = useState([]);
  const [pageCount, setPageCount] = useState(0);
  const [currentPage, setCurrentPage] = useState(0);
  const PER_PAGE = 3; // number of items to display per page
  const [error, setError] = useState("");

  useEffect(() => {
    // GET request
    fetch(`/get-friends/${name}`)
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
        if (data && data.friends.length === 0) {
          setError(`Hi ${name}! You have zero friends Requests`);
        } else {
          console.log(data);
          setFriends(data.friends);
          setPageCount(Math.ceil(data.friends.length / PER_PAGE));
        }
      })
      .catch((err) => {
        console.error(err);
        setError("Error fetching pending friends");
      });
  }, []);

  const handlePageClick = ({ selected: selectedPage }) => {
    setCurrentPage(selectedPage);
  };

  // Calculates the offset
  const offset = currentPage * PER_PAGE;

  // Autogenerated content for table
  const currentFriends = friends
    .slice(offset, offset + PER_PAGE)
    .map((friend) => (
      <tr
        key={friend.id}
        className="bg-blue-500 border-b border-blue-700 text-white font-semibold"
      >
        <td className="px-6 py-4">{friend.username}</td>
        <td className="px-6 py-4">{friend.name}</td>
        <td className="px-6 py-4">{friend.tasks}</td>
        <td className="px-6 py-4">{friend.tasksAccomplished}</td>
        <td className="px-6 py-4">{friend.weeklyTasks}</td>
        <td className="px-6 py-4">{friend.weeklyTasksAccomplished}</td>
      </tr>
    ));

  // returns jsx code
  if (error === "Error fetching pending friends") {
    return (
      <div>
        <p className="font-bold text-md text-gray-600 mt-6 mx-8">{error}</p>
      </div>
    );
  }

  // returns jsx code
  if (friends.length !== 0) {
    return (
      <div>
        <div className="relative overflow-x-auto mx-10 mt-10 rounded-md">
          <table className="w-full text-md text-left text-white">
            <thead className="text-xs text-white uppercase bg-blue-700">
              <tr>
                <th className="px-6 py-3">User</th>
                <th className="px-6 py-3">Name</th>
                <th className="px-6 py-3">Total Tasks</th>
                <th className="px-6 py-3">Total Accomplished Tasks</th>
                <th className="px-6 py-3">Total Weekly Tasks</th>
                <th className="px-6 py-3">Total Accomplished Weekly Tasks</th>
              </tr>
            </thead>
            <tbody>{currentFriends}</tbody>
          </table>
        </div>
        <div className="flex flex-row justify-center my-10">
          <ReactPaginate
            previousLabel={"← Previous"}
            nextLabel={"Next →"}
            pageCount={pageCount}
            onPageChange={handlePageClick}
            containerClassName={"flex space-x-4"}
            previousLinkClassName={
              "bg-blue-500 px-3 py-2 rounded-md text-md font-bold text-white"
            }
            nextLinkClassName={
              "bg-blue-500 px-3 py-2 rounded-md text-md font-bold text-white"
            }
            disabledClassName={"disabled"}
            activeClassName={
              "bg-blue-500 text-white px-3 py-1 rounded-md text-sm font-medium"
            }
          />
        </div>
      </div>
    );
  } else {
    // returns jsx code
    return (
      <div>
        <p className="font-bold text-md text-gray-600 mt-6 mx-8">
          You don't have any friends at the moment
        </p>
      </div>
    );
  }
}

export default ViewFriends;
