// Jose Bernardo Montano
// Jaret Raymond Rickel
// Annie Corinne Beaupre
import React, { useState, useEffect } from "react";
import ReactPaginate from "react-paginate";

// View Orgs shows a table that will show the organizations
// you are apart of and some data
function ViewOrgs({ name }) {
  // Hooks needed
  const [orgs, setOrgs] = useState([]);
  const [pageCount, setPageCount] = useState(0);
  const [currentPage, setCurrentPage] = useState(0);
  const PER_PAGE = 5; // number of items to display per page
  const [error, setError] = useState("");

  useEffect(() => {
    console.log(name);
    // GET request
    fetch(`/get-my-orgs/${name}`)
      .then((res) => res.json())
      .then((data) => {
        if (data && data.organizations.length === 0) {
          setError(`Hi ${name}! You are not part of any organization`);
        } else {
          console.log(data);
          setOrgs(data.organizations);
          setPageCount(Math.ceil(data.organizations.length / PER_PAGE));
        }
      })
      .catch((err) => {
        console.error(err);
        setError("Error fetching organizations requests");
      });
  }, []);

  const handlePageClick = ({ selected: selectedPage }) => {
    setCurrentPage(selectedPage);
  };

  // Calculates offset
  const offset = currentPage * PER_PAGE;

  // Autogenerated content for table
  const currentOrgs = orgs.slice(offset, offset + PER_PAGE).map((org) => (
    <tr
      key={org.id}
      className="bg-blue-500 border-b border-blue-700 text-white font-semibold"
    >
      <td className="px-6 py-4">{org.name}</td>
      <td className="px-6 py-4">{org.leaderName}</td>
      <td className="px-6 py-4">{org.people.length}</td>
    </tr>
  ));

  // Returns jsx code
  if (error === "Error fetching pending friends") {
    return (
      <div>
        <p className="font-bold text-md text-gray-600 mt-6 mx-8">{error}</p>
      </div>
    );
  }

  // Returns jsx code
  if (orgs.length !== 0) {
    return (
      <div>
        <div className="relative overflow-x-auto mx-10 mt-10 rounded-md">
          <table className="w-full text-md text-left text-white">
            <thead className="text-xs text-white uppercase bg-blue-700">
              <tr>
                <th className="px-6 py-3">Organization</th>
                <th className="px-6 py-3">Leader</th>
                <th className="px-6 py-3">Size of Organization</th>
              </tr>
            </thead>
            <tbody>{currentOrgs}</tbody>
          </table>
        </div>
        <div className="flex flex-row justify-center my-10">
          <ReactPaginate
            previousLabel={"← Previous"}
            nextLabel={"Next →"}
            pageCount={pageCount}
            onPageChange={handlePageClick}
            containerClassName={"flex space-x-4"}
            previousLinkClassName={
              "bg-blue-500 px-3 py-2 rounded-md text-md font-bold text-white"
            }
            nextLinkClassName={
              "bg-blue-500 px-3 py-2 rounded-md text-md font-bold text-white"
            }
            disabledClassName={"disabled"}
            activeClassName={
              "bg-blue-500 text-white px-3 py-1 rounded-md text-sm font-medium"
            }
          />
        </div>
      </div>
    );
  } else {
    return (
      <div>
        <p className="font-bold text-md text-gray-600 mt-6 mx-8">
          You are not part of any organization.
        </p>
      </div>
    );
  }
}

export default ViewOrgs;
